In [3]:
import numpy as np

In [2]:
import sys
import heapq

In [3]:
v=10
diameter=200
cab=[sys.maxsize]*4
heapInd=0
graph=np.random.randint(0,500, size=(v, v))
heapq.heapify(cab)
start=1
end=5

In [4]:
print(graph)

[[492  70 473 253 391 385   9  86 279  68]
 [236 100 136 297 240 213  38   9  84  11]
 [ 52 103 238 300 262   0 244 389 179  96]
 [180 164  61 223 418 317 387 359 177  32]
 [285 152 439 273  46 300 402 166 326  98]
 [397 449 289 250 274  81 266 418 306 445]
 [285 495 396 352  43 471 274 218 121  87]
 [ 35 445 400 330 388   1 355 120 268 331]
 [360  52 209 170 204 365 431 315 268 179]
 [485 398 401 409 219 425 206 426  93  47]]


In [5]:
dist = [sys.maxsize] *v
visited=[False] *v
dist[start]=0

#visited[start]=True
for i in range(v):
    index=0
    mini=sys.maxsize
    for u in range (v):
        if dist[u]<mini and visited[u]==False:
            mini=dist[u]
            index=u  
                  
       
    visited[index]=True
    for j in range(v):
        if graph[index][j]!=0 and visited[j]==False and dist[j]>(dist[index] + graph[index][j]):
            dist[j]=(dist[index] + graph[index][j])
            
            #cab
            if dist[j]<diameter:
                if heapInd<len(cab):
                    
                    cab[heapInd]=dist[j]
                    heapInd+=1
                elif heapInd>=len(cab) and dist[j]<heapq.nlargest(1,cab):
                    num=heapq.nlargest(1,cab)
                    indx=cab.index(num)
                    cab[indx]=dist[j] 
       
            
            
        
print(dist)
print(cab)   

[44, 0, 136, 254, 81, 10, 38, 9, 84, 11]
[11, 38, 9, 10]


In [6]:
n=len(cab)
cabDistance=0
heapq.heapify(cab)
print(cab)

[9, 10, 11, 38]


In [7]:
for i in range(n):
    accept=np.random.randint(0,2, size=(1, 1))
    if accept==0:
        print(accept)
        heapq.heappop(cab)
    else:
        print(accept)
        print(cab)
        cabDistance=cab[0]
        break       

[[0]]
[[0]]
[[0]]
[[1]]
[38]


In [8]:
print("source to destination distance ",dist[end],"meter")

source to destination distance  10 meter


In [9]:
print("source to cab distance ",cabDistance,"meter")

source to can distance  38 miter


In [10]:
#add traffic
traffic=np.random.randint(0, 50)
print(traffic)

11


In [11]:
#time to reach driver

your driver will reach within  1.225 minutes


In [1]:
st={}

In [8]:
st=np.random.randint(0, 50,size=(1,4))

In [9]:
print(st)

[[ 7  8 23 30]]


In [11]:
if 8 in st:
  print("Yes,  is in this set")

Yes, 'apple' is in this set
